# Spotify Notebook

In [ ]:
%pip install kaggle

In [17]:
# ---------------------------------------------------------
# 2. Verify that kaggle.json exists
#    It should be located at ~/.kaggle/kaggle.json
# ---------------------------------------------------------
import os

kaggle_path = os.path.expanduser("~/.kaggle/kaggle.json")
if os.path.exists(kaggle_path):
    print("Kaggle API key found.")
else:
    print("Kaggle API key NOT found. Please place kaggle.json in ~/.kaggle/")

Kaggle API key found.

In [18]:
# ---------------------------------------------------------
# 3. Download the dataset from Kaggle
# ---------------------------------------------------------
!kaggle datasets download -d anxods/spotify-top-50-playlist-songs-anxods

Dataset URL: https://www.kaggle.com/datasets/anxods/spotify-top-50-playlist-songs-anxods
License(s): CC-BY-NC-SA-4.0
Downloading spotify-top-50-playlist-songs-anxods.zip to /Users/gerardo/Projects/jupyter-notebooks
 57%|█████████████████████▌                | 1.00M/1.76M [00:00<00:00, 3.06MB/s]
100%|██████████████████████████████████████| 1.76M/1.76M [00:00<00:00, 4.27MB/s]

In [19]:
# ---------------------------------------------------------
# 4. Unzip the dataset into a folder
# ---------------------------------------------------------
import zipfile

zip_file = "spotify-top-50-playlist-songs-anxods.zip"
extract_folder = "spotify_data"

with zipfile.ZipFile(zip_file, "r") as z:
    z.extractall(extract_folder)

print("Files extracted to:", extract_folder)

Files extracted to: spotify_data

In [24]:
# ---------------------------------------------------------
# 5. Load the dataset with pandas
# ---------------------------------------------------------
import os
import pandas as pd

extract_folder = "spotify_data"
data_folder = os.path.join(extract_folder, "data")

# List all CSV files inside spotify_data/data/
csv_files = [f for f in os.listdir(data_folder) if f.endswith(".csv")]

csv_files

['spotify-streaming-top-50-spain.csv',
 'spotify-streaming-top-50-italy.csv',
 'spotify-streaming-top-50-usa.csv',
 'spotify-streaming-top-50-south-korea.csv',
 'spotify-streaming-top-50-japan.csv',
 'spotify-streaming-top-50-uk.csv',
 'spotify-streaming-top-50-argentina.csv',
 'spotify-streaming-top-50-world.csv',
 'spotify-streaming-top-50-mexico.csv',
 'spotify-streaming-top-50-france.csv']

In [25]:
# ---------------------------------------------------------
# 6. Read the CSV (adjust filename if needed)
# ---------------------------------------------------------
df = pd.read_csv(os.path.join(data_folder, "spotify-streaming-top-50-usa.csv"))
df.head()

,date,position,song,artist,popularity,duration_ms,album_type,total_tracks,release_date,is_explicit,album_cover_url
0,2023-05-18,1,Ella Baila Sola,Eslabon Armado,89,165671,album,16,2023-04-28,False,https://i.scdn.co/image/ab67616d0000b273dfddf1...
1,2023-05-18,2,Last Night,Morgan Wallen,89,163854,album,36,2023-03-03,True,https://i.scdn.co/image/ab67616d0000b273705079...
2,2023-05-18,3,All My Life (feat. J. Cole),Lil Durk & J. Cole,84,223878,single,1,2023-05-12,True,https://i.scdn.co/image/ab67616d0000b2737c173b...
3,2023-05-18,4,un x100to,Grupo Frontera & Bad Bunny,99,194563,single,1,2023-04-17,False,https://i.scdn.co/image/ab67616d0000b273716c0b...
4,2023-05-18,5,Kill Bill,SZA,94,153946,album,23,2022-12-08,False,https://i.scdn.co/image/ab67616d0000b2730c471c...

In [26]:
dfs = {}

for file in csv_files:
    path = os.path.join(data_folder, file)
    dfs[file] = pd.read_csv(path)

dfs.keys()
dfs["spotify-streaming-top-50-usa.csv"].head()

,date,position,song,artist,popularity,duration_ms,album_type,total_tracks,release_date,is_explicit,album_cover_url
0,2023-05-18,1,Ella Baila Sola,Eslabon Armado,89,165671,album,16,2023-04-28,False,https://i.scdn.co/image/ab67616d0000b273dfddf1...
1,2023-05-18,2,Last Night,Morgan Wallen,89,163854,album,36,2023-03-03,True,https://i.scdn.co/image/ab67616d0000b273705079...
2,2023-05-18,3,All My Life (feat. J. Cole),Lil Durk & J. Cole,84,223878,single,1,2023-05-12,True,https://i.scdn.co/image/ab67616d0000b2737c173b...
3,2023-05-18,4,un x100to,Grupo Frontera & Bad Bunny,99,194563,single,1,2023-04-17,False,https://i.scdn.co/image/ab67616d0000b273716c0b...
4,2023-05-18,5,Kill Bill,SZA,94,153946,album,23,2022-12-08,False,https://i.scdn.co/image/ab67616d0000b2730c471c...